pull_request_rules:
  - name: automatic merge when CI passes and 2 reviews
    conditions:
      - author=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - base=master
    actions:
      merge:
        method: merge
